export const FETCH_LIST_TASK = "FETCH_LIST_TASK"
export const FETCH_LIST_TASK_ERROR = "FETCH_LIST_TASK_ERROR"
export const FETCH_LIST_TASK_SUCCESS = "FETCH_LIST_TASK_SUCCESS"

export const FILTER_TASK = "FILTER_TASK"
export const FILTER_TASK_SUCCESS = "FILTER_TASK_SUCCESS"


export const ADD_TASK = "ADD_TASK"
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAIL = "ADD_TASK_FAIL"


export const DELETE_TASK ="DELETE_TASK";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL ="DELETE_TASK_FAIL"



export const EDIT_TASK ="EDIT_TASK";
export const EDIT_SUCCESS ="EDIT_SUCCESS";
export const EDIT_TASK_FAIL ="EDIT_TASK_FAIL";
